### ISSUE TITLE
socker_server这个是module还是啥？咋用的

### ISSUE THREAD

**Issue by raylee2012** [jiusetian/EasySocket#1]
socker_server这个是module还是啥？咋用的

**Comment by jiusetian** [comment]
这是一个服务端的测试代码，用来测试项目功能使用的，在Android Studio中运行它即可

**Comment by raylee2012** [comment]
> 这是一个服务端的测试代码，用来测试项目功能使用的，在Android Studio中运行它即可
貌似不是一个module，怎么运行呀？javac吗？

**Comment by jiusetian** [comment]
Android studio中不是有运行项目的选择吗，就是app字样那里有个下拉箭头的，你点开选择这个服务端项目运行即可

**Comment by jiusetian** [comment]
不过你要先Edit Configurations那里添加的，具体怎么操作可以去百度一下Android studio如何运行Java项目

**Comment by raylee2012** [comment]
> 不过你要先Edit Configurations那里添加的，具体怎么操作可以去百度一下Android studio如何运行Java项目
as编译完后，只有app一个module可以运行。我直接从这里clone的工程。

**Comment by raylee2012** [comment]
> ations那里添加的，具体怎么操作可以去百度一下Android

好的，我试试
