### ISSUE TITLE
当读错误发生时

### ISSUE THREAD

**Issue by phoebewow** [jiusetian/EasySocket#19]
W/System.err: easysocket：com.easysocket.connection.iowork.EasyReader$1 run():192 读数据异常 
W/System.err: com.easysocket.entity.exception.SocketReadExeption: 读数据失败，可能是因为socket跟服务器断开了连接
W/System.err:     at com.easysocket.connection.iowork.EasyReader.readHeaderFromSteam(EasyReader.java:210)
W/System.err:     at com.easysocket.connection.iowork.EasyReader.read(EasyReader.java:99)
W/System.err:     at com.easysocket.connection.iowork.EasyReader$1.run(EasyReader.java:189)
        at java.lang.Thread.run(Thread.java:923)
        
当出现这个错误的时候，客户端状态是否应该转为断连状态，或者自动重新连接socket
这个错误出现的原因是，我连接上socket之后就一直在等待服务器自动发送过来的数据，一直没等到，我也没往服务器发送数据

**Comment by jiusetian** [comment]
> 
> 
> W/System.err: easysocket：com.easysocket.connection.iowork.EasyReader$1 run():192 读数据异常
> W/System.err: com.easysocket.entity.exception.SocketReadExeption: 读数据失败，可能是因为socket跟服务器断开了连接
> W/System.err: at com.easysocket.connection.iowork.EasyReader.readHeaderFromSteam(EasyReader.java:210)
> W/System.err: at com.easysocket.connection.iowork.EasyReader.read(EasyReader.java:99)
> W/System.err: at com.easysocket.connection.iowork.EasyReader$1.run(EasyReader.java:189)
> at java.lang.Thread.run(Thread.java:923)
> 
> 当出现这个错误的时候，客户端状态是否应该转为断连状态，或者自动重新连接socket
> 这个错误出现的原因是，我连接上socket之后就一直在等待服务器自动发送过来的数据，一直没等到，我也没往服务器发送数据

确实有你说的这个问题，当初设计的时候可能考虑得不合理，现在已经修复了，你可以试试v1.8.6版

**Comment by phoebewow** [comment]
ok了，已会自动重连，谢谢
