### ISSUE TITLE
首次连接成功后，服务端这时候有回执消息，这个消息接收不了，，，

### ISSUE THREAD

**Issue by lianghao721** [jiusetian/EasySocket#20]
首次连接成功后，硬件设备服务端会回传一些初始化状态给我，框架里首次接收的消息好像是不处理滴。

**Comment by jiusetian** [comment]
> 
> 
> 首次连接成功后，硬件设备服务端会回传一些初始化状态给我，框架里首次接收的消息好像是不处理滴。

是没接到消息还是接收到了没处理，有什么异常吗，有设置消息协议吗

**Comment by lianghao721** [comment]
昨天用的1.6.6版本，连接成功后，木有接收到硬件设备服务器发送过来的数据，我这样子自己拿到InputputStream然后读取，能够读取到。。。。
 这个问题没关系了。。
 /**
     * socket行为监听
     */
    private ISocketActionListener socketActionListener = new SocketActionListener() {
        /**
         * socket连接成功
         */
        @Override
        public void onSocketConnSuccess(SocketAddress socketAddress) {
            super.onSocketConnSuccess(socketAddress);
            Log.e("easysocket", "---连接成功");
            toolbar.setTitle("连接成功");
            new Thread(new Runnable() {
                @Override
                public void run() {
                    byte[] buff = new byte[3];
                    BufferedInputStream br = new BufferedInputStream(EasySocket.getInstance().getConnection().getInputStream());
                    int read = 0;
                    try {
                        read = br.read(buff, 0, 3);
                        if (read > 0) {
                            Log.e("easysocket", "----------------run: " + Arrays.toString(buff));
                        }
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                }
            }).start();
            isConnected = true;
        }

今天发现有1.8.6，然后升级试了试，发现个问题。
@Override
        public void onSocketConnFail(SocketAddress socketAddress, boolean isNeedReconnect) {
            super.onSocketConnFail(socketAddress, false);
            Log.e("easysocket", "---连接失败");
        }

        @Override
        public void onSocketDisconnect(SocketAddress socketAddress, boolean isNeedReconnect) {
            super.onSocketDisconnect(socketAddress, false);
            Log.e("easysocket", "---断开连接");
        }
当心跳连接超时失败，或者连接断开后，这样子置为false不让重连，不起作用，依然会重新连接哟。

**Comment by jiusetian** [comment]
这样设置我不起作用的，本身这函数
@Override
    public void onSocketDisconnect(SocketAddress socketAddress, boolean isNeedReconnect) {
        super.onSocketDisconnect(socketAddress, false);
        Log.e("easysocket", "---断开连接");
    }
的isNeedReconnect参数不是让你设置是否需要重连，只是告诉你当前断开的连接是否需要重连，这不是你来设置的，框架在默认情况下，所有的意外的原因断开的连接都是默认需要重连的，除非一些人为的因素或者错误，比如你心跳连接超时，默认情况下是需要重连的，因为这个认为是意外的原因，还有你自己主动断开连接的时候，可以设置是否需要重连：com.easysocket.EasySocket#disconnect(boolean isNeedReconnect)，如果你想在不管什么原因断开连接都不需要重连的话，可能需要改造一下

**Comment by jiusetian** [comment]
如果你觉得这个断开不需要重连，可以这样设置
    @Override
    public void onSocketDisconnect(SocketAddress socketAddress, boolean isNeedReconnect) {
        super.onSocketDisconnect(socketAddress, false);
           // 如果不需要重连，即断开连接不重连
            if (isNeedReconnect){
                EasySocket.getInstance().disconnect(false);
            }
        Log.e("easysocket", "---断开连接");
    }
应该有用

**Comment by lianghao721** [comment]
> 如果你觉得这个断开不需要重连，可以这样设置
> @override
> public void onSocketDisconnect(SocketAddress socketAddress, boolean isNeedReconnect) {
> super.onSocketDisconnect(socketAddress, false);
> // 如果不需要重连，即断开连接不重连
> if (isNeedReconnect){
> EasySocket.getInstance().disconnect(false);
> }
> Log.e("easysocket", "---断开连接");
> }
> 应该有用

orz，感谢，

**Comment by lianghao721** [comment]
// 如果不需要重连，即断开连接不重连
if (isNeedReconnect){
EasySocket.getInstance().disconnect(false);
}

这样子是不起左右的。。。
