### ISSUE TITLE
wifi断开连接，socket还在傻傻的重新连接。

### ISSUE THREAD

**Issue by lianghao721** [jiusetian/EasySocket#22]
wifi断开，并且页面退出时 设置了  EasySocket.getInstance().destroyConnection();  socket还在傻傻的无线重连。。
回收机制不完善哟。

重连最好是可以设置重连次数，超过次数后，自动停止连接，回收内存
拜谢~

**Comment by lianghao721** [comment]
问题补充

  退出页面时调用EasySocket.getInstance().destroyConnection(); 
  分发队列内存溢出

  │ GC Root: Local variable in native code
    │
    ├─ com.easysocket.connection.dispatcher.SocketActionDispatcher$DispatchThread instance
    │    Leaking: UNKNOWN
    │    Retaining 356 bytes in 11 objects
    │    Thread name: 'dispatch thread'
    │    ↓ SocketActionDispatcher$DispatchThread.this$0
    │                                            ~~~~~~
    ├─ com.easysocket.connection.dispatcher.SocketActionDispatcher instance
    │    Leaking: UNKNOWN
    │    Retaining 480569 bytes in 43 objects
    │    ↓ SocketActionDispatcher.actionListeners
    │                             ~~~~~~~~~~~~~~~
    ├─ java.util.ArrayList instance
    │    Leaking: UNKNOWN
    │    Retaining 480503 bytes in 40 objects
    │    ↓ ArrayList.elementData
    │                ~~~~~~~~~~~
    ├─ java.lang.Object[] array
    │    Leaking: UNKNOWN
    │    Retaining 480483 bytes in 39 objects
    │    ↓ Object[].[1]
    │               ~~~
    ├─ com.snake.seneschal.ui.pipehouse.pipe_internal_corrosion_inspection.ConnectActivity$1 instance
    │    Leaking: UNKNOWN
    │    Retaining 399954 bytes in 6552 objects
    │    Anonymous subclass of com.easysocket.interfaces.conn.SocketActionListener
    │    this$0 instance of com.snake.seneschal.ui.pipehouse.pipe_internal_corrosion_inspection.ConnectActivity with
    │    mDestroyed = true
    │    ↓ ConnectActivity$1.this$0
    │                        ~~~~~~
    ╰→ com.snake.seneschal.ui.pipehouse.pipe_internal_corrosion_inspection.ConnectActivity instance
    ​     Leaking: YES (Obje

**Comment by jiusetian** [comment]
其他两个问题我都已经做了修复，当时关于“重连最好是可以设置重连次数，超过次数后，自动停止连接，回收内存”这个问题，我觉得没必要修复，因为socket本来的意义就是保持长连接，如果因为重连超过一定次数就停止连接，那么当有条件重连成功的时候，socket是不会主动去重连的，所以这个问题没必要纠结，你可以自己去设置，监听socket的来连接失败的次数，然后destroyConnection()即可，当有需要再次重连的时候，你可以创建一个连接

**Comment by lianghao721** [comment]
嗯，我重寫了重連接口后，到達次數后，就自動停止鏈接了
`    @Override
    public void onSocketConnFail(SocketAddress socketAddress, boolean isNeedReconnect) {
        // 不需要重连，则关闭重连线程
        if (!isNeedReconnect) {
            shutDown();
            return;
        }
        connectionFailedTimes++;

        // 如果大于最大连接次数并且有备用host,则轮流切换两个host
        if (connectionFailedTimes > MAX_CONNECTION_FAILED_TIMES && socketAddress.getBackupAddress() != null) {
            connectionFailedTimes = 0; // 归零
            SocketAddress backupAddress = socketAddress.getBackupAddress();
            SocketAddress nowAddress = new SocketAddress(socketAddress.getIp(), socketAddress.getPort());
            backupAddress.setBackupAddress(nowAddress);
            if (connectionManager.isConnectViable()) {
                connectionManager.switchHost(backupAddress);
                // 切换主机地址，重新连接
                reconnect();
            }
        } else {
            if (connectionFailedTimes > MAX_CONNECTION_FAILED_TIMES) {
                LogUtil.e("已重连次数--onSocketConnFail-> " + connectionFailedTimes);
                connectionFailedTimes = 0; // 归零
                shutDown();
                return;
            }
            reconnect();
        }
    }

    @Override
    public void onSocketDisconnect(SocketAddress socketAddress, boolean isNeedReconnect) {
        // 是否需要重连
        if (!isNeedReconnect) {
            shutDown();
            return;
        }
        connectionFailedTimes++;
        if (connectionFailedTimes >= MAX_CONNECTION_FAILED_TIMES) {
            LogUtil.e("已重连次数--onSocketDisconnect-> " + connectionFailedTimes);
            connectionFailedTimes = 0; // 归零
            shutDown();
            return;
        }
        reconnect();
    }`
