### ISSUE TITLE
没有这个方法

### ISSUE THREAD

**Issue by zhao841359690** [jiusetian/EasySocket#6]
new EasySocketOptions.Builder() .setSocketAddress（）

**Comment by zhao841359690** [comment]
现在是直接.ip吗？希望能更新一下文档，太误导了

**Comment by jiusetian** [comment]
> new EasySocketOptions.Builder() .setSocketAddress（）

现在是1.6.2的版本，新版的才有这个方法

**Comment by zhao841359690** [comment]
好的，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"jiusetian"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月13日(星期一) 中午11:36
收件人:&nbsp;"jiusetian/EasySocket"<EasySocket@noreply.github.com&gt;;
抄送:&nbsp;"继续、沈默"<841359690@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [jiusetian/EasySocket] 没有这个方法 (#6)





  
new EasySocketOptions.Builder() .setSocketAddress（）
  
现在是1.6.2的版本，新版的才有这个方法

**Comment by jiusetian** [comment]
> 好的，谢谢
> 
> 
> 
> 
> 
> 
> 
> 
> 
> ------------------&nbsp;原始邮件&nbsp;------------------
> 
> 发件人:&nbsp;"jiusetian"<notifications@github.com&gt;;
> 
> 发送时间:&nbsp;2020年4月13日(星期一) 中午11:36
> 
> 收件人:&nbsp;"jiusetian/EasySocket"<EasySocket@noreply.github.com&gt;;
> 
> 抄送:&nbsp;"继续、沈默"<841359690@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
> 
> 主题:&nbsp;Re: [jiusetian/EasySocket] 没有这个方法 (#6)
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
>   
> 
> new EasySocketOptions.Builder() .setSocketAddress（）
> 
>   
> 
> 现在是1.6.2的版本，新版的才有这个方法
> 
>  
> 
> —
> 
> You are receiving this because you authored the thread.
> 
> Reply to this email directly, view it on GitHub, or unsubscribe.

不好意思，是1. 6. 3

**Comment by zhao841359690** [comment]
为什么每次发送数据，就会disconnect啊

**Comment by jiusetian** [comment]
> 为什么每次发送数据，就会disconnect啊

有什么log吗，不然我也不知道什么原因

**Comment by zhao841359690** [comment]
服务器返回的单次数据超过了规定的最大值，可能你的Socket消息的数据格式不对，本项目默认的消息格式为：Header+Body，消息头Header保存消息的长度，一般长度为一个int，Body保存消息内容，请规范好相关协议  这个协议的规范是什么

**Comment by jiusetian** [comment]
就是说你跟后台发送的socket消息的数据格式，比如项目默认的消息格式是：Header+Body，Header保存消息的长度，Header默认为一个int，Body保存消息内容，比如你给后台或者后台给你发送一个消息为"hello"的时候，你首先得把hello的字节长度保存在消息头Header中，然后把hello这个内容保存到消息的Body中，然后把打包好的消息发送出去，如果你不按这个格式打包消息，机会出现上面的问题，无法解析消息的内容

**Comment by zhao841359690** [comment]
那可以只发送body 吗？

**Comment by jiusetian** [comment]
只发body我们解析不出来，因为我要知道你发的body的长度，不然当你的消息出现分包或者粘包的时候，就会出现混乱

**Comment by zhao841359690** [comment]
好的，谢谢🙏
