### ISSUE TITLE
请问服务器返回的数据格式应如何组装？

### ISSUE THREAD

**Issue by Coolkkmeat** [jiusetian/EasySocket#9]
用的是Swoole框架做服务端，查看了一下issue是 包头+包体。
这个意思是比如：`0004test`然后取bytes？但是还是提示格式不对。
刚学Socket开发，不太明白，求指教，谢谢。

**Comment by jiusetian** [comment]
我这里的数据格式也是包头+包体，包头默认的一个int，保存数据的长度，包体保存数据，如果按照这种格式的话数据解析是没有问题的，然后数据本身的格式默认是json

**Comment by Coolkkmeat** [comment]
> 我这里的数据格式也是包头+包体，包头默认的一个int，保存数据的长度，包体保存数据，如果按照这种格式的话数据解析是没有问题的，然后数据本身的格式默认是json

感谢，成功发送和接收了。
有几个小问题：
1.客户端发出去的数据是不是没有用这个格式？
2.接收数据最多支持多长，log显示最多到2644，不知道是客户端还是服务端的限制。
3.能否设置不进行log输出，看到配置里有isDebug，好像只能获取而无法设定。
4.包头是否有位数限制，还是只要是int就可以？
5.重连最大次数是多少？在一次测试的时候，不知道哪里的问题，客户端不断连接然后断开停不下来。
6.是否可以自定义协议。
感谢解答。

**Comment by jiusetian** [comment]
> > 我这里的数据格式也是包头+包体，包头默认的一个int，保存数据的长度，包体保存数据，如果按照这种格式的话数据解析是没有问题的，然后数据本身的格式默认是json
> 
> 感谢，成功发送和接收了。
> 有几个小问题：
> 1.客户端发出去的数据是不是没有用这个格式？
> 2.接收数据最多支持多长，log显示最多到2644，不知道是客户端还是服务端的限制。
> 3.能否设置不进行log输出，看到配置里有isDebug，好像只能获取而无法设定。
> 4.包头是否有位数限制，还是只要是int就可以？
> 5.重连最大次数是多少？在一次测试的时候，不知道哪里的问题，客户端不断连接然后断开停不下来。
> 6.是否可以自定义协议。
> 感谢解答。

客户端也是用这种格式，数据单次接收的最大长度默认是50Mb吧，这个可以设置的，有setIsDebug方法设置是否输出log，数据协议可以自己定义，但是要实现框架的接口IMessageProtocol，有一个默认的协议DefaultMessageProtocol，关于重连，如果你开启了心跳保活机制才会自动重连，如果一定时间没有收到服务端的心跳包客户端就会进行重连

**Comment by Coolkkmeat** [comment]
感谢，明白了。
重连这里，我用的代码如下（基本都是readme里的），没有开启心跳，还是会自动重连。
```java
public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        //
        //EasySocket.配置
        EasySocketOptions options = new EasySocketOptions.Builder()
                .setSocketAddress(new SocketAddress("192.168.1.2", 19000))
                .build();
        //EasySocket.创建
        EasySocket.getInstance()
                .options(options)
                .createConnection();
        //EasySocket.接收
        EasySocket.getInstance().subscribeSocketAction(new SocketActionListener() {
            @Override
            public void onSocketConnSuccess(SocketAddress socketAddress) {
                super.onSocketConnSuccess(socketAddress);
                //LogUtil.d("连接成功");
            }

            @Override
            public void onSocketConnFail(SocketAddress socketAddress, Boolean isReconnect) {
                super.onSocketConnFail(socketAddress, isReconnect);
            }

            @Override
            public void onSocketDisconnect(SocketAddress socketAddress, Boolean isReconnect) {
                super.onSocketDisconnect(socketAddress, isReconnect);
            }

            @Override
            public void onSocketResponse(SocketAddress socketAddress, OriginReadData originReadData) {
                super.onSocketResponse(socketAddress, originReadData);
                //LogUtil.d("socket监听器收到数据=" + originReadData.getBodyString());
            }
        });
        //EasySocket.连接
        EasySocket.getInstance().connect();
        //EasySocket.断开
        //EasySocket.getInstance().disconnect(false);
        //EasySocket.发送
        EasySocket.getInstance().upObject(new ISender() {
            @Override
            public byte[] parse() {
                return "test".getBytes();
            }
        });
        //EasySocket.销毁
        //EasySocket.getInstance().destroyConnection();
    }

}
```
```
2020-06-14 17:47:17.093 31130-31130/net.coolkk.test I/System.out: easysocket：com.easysocket.connection.connect.SuperConnection connect():118 开始socket连接 
2020-06-14 17:47:17.094 31130-31130/net.coolkk.test I/System.out: easysocket：com.easysocket.connection.connect.SuperConnection connect():118 开始socket连接 
2020-06-14 17:47:17.094 31130-31130/net.coolkk.test I/System.out: easysocket：com.easysocket.connection.connect.SuperConnection connect():121 socket已连接 
2020-06-14 17:47:17.102 31130-31215/net.coolkk.test W/System.err:     at com.easysocket.connection.connect.TcpConnection.openConnection(TcpConnection.java:46)
2020-06-14 17:47:17.102 31130-31215/net.coolkk.test W/System.err:     at com.easysocket.connection.connect.SuperConnection$ConnectThread.run(SuperConnection.java:207)
2020-06-14 17:47:17.103 31130-31215/net.coolkk.test I/System.out: easysocket：com.easysocket.connection.connect.SuperConnection$ConnectThread run():211 socket连接失败 
2020-06-14 17:47:17.113 31130-31216/net.coolkk.test I/System.out: easysocket：com.easysocket.connection.reconnect.DefaultReConnection$1 run():42 执行重连 
2020-06-14 17:47:17.113 31130-31216/net.coolkk.test I/System.out: easysocket：com.easysocket.connection.connect.SuperConnection connect():118 开始socket连接 
2020-06-14 17:47:17.122 31130-31217/net.coolkk.test W/System.err:     at com.easysocket.connection.connect.TcpConnection.openConnection(TcpConnection.java:46)
2020-06-14 17:47:17.122 31130-31217/net.coolkk.test W/System.err:     at com.easysocket.connection.connect.SuperConnection$ConnectThread.run(SuperConnection.java:207)
2020-06-14 17:47:17.122 31130-31217/net.coolkk.test I/System.out: easysocket：com.easysocket.connection.connect.SuperConnection$ConnectThread run():211 socket连接失败 
2020-06-14 17:47:19.590 31130-31171/net.coolkk.test I/System.out: easysocket：com.easysocket.connection.reconnect.DefaultReConnection$1 run():42 执行重连 
2020-06-14 17:47:27.116 31130-31216/net.coolkk.test I/System.out: easysocket：com.easysocket.connection.reconnect.DefaultReConnection$1 run():42 执行重连 
2020-06-14 17:47:27.116 31130-31216/net.coolkk.test I/System.out: easysocket：com.easysocket.connection.connect.SuperConnection connect():118 开始socket连接 
2020-06-14 17:47:27.129 31130-31246/net.coolkk.test W/System.err:     at com.easysocket.connection.connect.TcpConnection.openConnection(TcpConnection.java:46)
2020-06-14 17:47:27.129 31130-31246/net.coolkk.test W/System.err:     at com.easysocket.connection.connect.SuperConnection$ConnectThread.run(SuperConnection.java:207)
2020-06-14 17:47:27.130 31130-31246/net.coolkk.test I/System.out: easysocket：com.easysocket.connection.connect.SuperConnection$ConnectThread run():211 socket连接失败 
```

**Comment by jiusetian** [comment]
你这里连接了两次socket，其实createConnection的时候已经进行了socket连接，你后面又调用了connect，第一次连接已经成功了，所以你第二次再连的时候就失败了，造成了重连，因为框架在交接失败的时候默认是自动重连的

**Comment by jiusetian** [comment]
> 感谢，明白了。
> 重连这里，我用的代码如下（基本都是readme里的），没有开启心跳，还是会自动重连。
> 
> ```java
> public class MainActivity extends AppCompatActivity {
> 
>     @Override
>     protected void onCreate(Bundle savedInstanceState) {
>         super.onCreate(savedInstanceState);
>         setContentView(R.layout.activity_main);
>         //
>         //EasySocket.配置
>         EasySocketOptions options = new EasySocketOptions.Builder()
>                 .setSocketAddress(new SocketAddress("192.168.1.2", 19000))
>                 .build();
>         //EasySocket.创建
>         EasySocket.getInstance()
>                 .options(options)
>                 .createConnection();
>         //EasySocket.接收
>         EasySocket.getInstance().subscribeSocketAction(new SocketActionListener() {
>             @Override
>             public void onSocketConnSuccess(SocketAddress socketAddress) {
>                 super.onSocketConnSuccess(socketAddress);
>                 //LogUtil.d("连接成功");
>             }
> 
>             @Override
>             public void onSocketConnFail(SocketAddress socketAddress, Boolean isReconnect) {
>                 super.onSocketConnFail(socketAddress, isReconnect);
>             }
> 
>             @Override
>             public void onSocketDisconnect(SocketAddress socketAddress, Boolean isReconnect) {
>                 super.onSocketDisconnect(socketAddress, isReconnect);
>             }
> 
>             @Override
>             public void onSocketResponse(SocketAddress socketAddress, OriginReadData originReadData) {
>                 super.onSocketResponse(socketAddress, originReadData);
>                 //LogUtil.d("socket监听器收到数据=" + originReadData.getBodyString());
>             }
>         });
>         //EasySocket.连接
>         EasySocket.getInstance().connect();
>         //EasySocket.断开
>         //EasySocket.getInstance().disconnect(false);
>         //EasySocket.发送
>         EasySocket.getInstance().upObject(new ISender() {
>             @Override
>             public byte[] parse() {
>                 return "test".getBytes();
>             }
>         });
>         //EasySocket.销毁
>         //EasySocket.getInstance().destroyConnection();
>     }
> 
> }
> ```
> 
> ```
> 2020-06-14 17:47:17.093 31130-31130/net.coolkk.test I/System.out: easysocket：com.easysocket.connection.connect.SuperConnection connect():118 开始socket连接 
> 2020-06-14 17:47:17.094 31130-31130/net.coolkk.test I/System.out: easysocket：com.easysocket.connection.connect.SuperConnection connect():118 开始socket连接 
> 2020-06-14 17:47:17.094 31130-31130/net.coolkk.test I/System.out: easysocket：com.easysocket.connection.connect.SuperConnection connect():121 socket已连接 
> 2020-06-14 17:47:17.102 31130-31215/net.coolkk.test W/System.err:     at com.easysocket.connection.connect.TcpConnection.openConnection(TcpConnection.java:46)
> 2020-06-14 17:47:17.102 31130-31215/net.coolkk.test W/System.err:     at com.easysocket.connection.connect.SuperConnection$ConnectThread.run(SuperConnection.java:207)
> 2020-06-14 17:47:17.103 31130-31215/net.coolkk.test I/System.out: easysocket：com.easysocket.connection.connect.SuperConnection$ConnectThread run():211 socket连接失败 
> 2020-06-14 17:47:17.113 31130-31216/net.coolkk.test I/System.out: easysocket：com.easysocket.connection.reconnect.DefaultReConnection$1 run():42 执行重连 
> 2020-06-14 17:47:17.113 31130-31216/net.coolkk.test I/System.out: easysocket：com.easysocket.connection.connect.SuperConnection connect():118 开始socket连接 
> 2020-06-14 17:47:17.122 31130-31217/net.coolkk.test W/System.err:     at com.easysocket.connection.connect.TcpConnection.openConnection(TcpConnection.java:46)
> 2020-06-14 17:47:17.122 31130-31217/net.coolkk.test W/System.err:     at com.easysocket.connection.connect.SuperConnection$ConnectThread.run(SuperConnection.java:207)
> 2020-06-14 17:47:17.122 31130-31217/net.coolkk.test I/System.out: easysocket：com.easysocket.connection.connect.SuperConnection$ConnectThread run():211 socket连接失败 
> 2020-06-14 17:47:19.590 31130-31171/net.coolkk.test I/System.out: easysocket：com.easysocket.connection.reconnect.DefaultReConnection$1 run():42 执行重连 
> 2020-06-14 17:47:27.116 31130-31216/net.coolkk.test I/System.out: easysocket：com.easysocket.connection.reconnect.DefaultReConnection$1 run():42 执行重连 
> 2020-06-14 17:47:27.116 31130-31216/net.coolkk.test I/System.out: easysocket：com.easysocket.connection.connect.SuperConnection connect():118 开始socket连接 
> 2020-06-14 17:47:27.129 31130-31246/net.coolkk.test W/System.err:     at com.easysocket.connection.connect.TcpConnection.openConnection(TcpConnection.java:46)
> 2020-06-14 17:47:27.129 31130-31246/net.coolkk.test W/System.err:     at com.easysocket.connection.connect.SuperConnection$ConnectThread.run(SuperConnection.java:207)
> 2020-06-14 17:47:27.130 31130-31246/net.coolkk.test I/System.out: easysocket：com.easysocket.connection.connect.SuperConnection$ConnectThread run():211 socket连接失败 
> ```

你这里连接了两次socket，其实createConnection的时候已经进行了socket连接，你后面又调用了connect，第一次连接已经成功了，所以你第二次再连的时候就失败了，造成了重连，因为框架在交接失败的时候默认是自动重连的

**Comment by Coolkkmeat** [comment]
> 你这里连接了两次socket，其实createConnection的时候已经进行了socket连接，你后面又调用了connect，第一次连接已经成功了，所以你第二次再连的时候就失败了，造成了重连，因为框架在交接失败的时候默认是自动重连的

请问`createConnection()`也起连接的作用吗？

**Comment by Coolkkmeat** [comment]
> 你这里连接了两次socket，其实createConnection的时候已经进行了socket连接，你后面又调用了connect，第一次连接已经成功了，所以你第二次再连的时候就失败了，造成了重连，因为框架在交接失败的时候默认是自动重连的

好的，非常感谢！问题都解决了。
